### ISSUE TITLE
**Non-Devs as CCs.** As an Open edX contributor who does _not_ code but has demonstrated **commitment**, good **conduct**, and high **caliber**, I would like to have higher privileges to increase my contributions.

### ISSUE THREAD

**Issue by nasthagiri** [edx/open-edx-proposals#215]

**Comment by gabrieldamours** [comment]
@sarina I'll start by taking a look at https://openedx.atlassian.net/wiki/spaces/COMM/pages/2759460357/Definition+of+non-code+Core+Committer, which you shared with the marketing work group today

**Comment by sarina** [comment]
@gabrieldamours great! Please put comments directly in that doc. Note that I'm collecting input through June, then meeting with Legal in early July to solidify definitions & legal needs, so I don't expect to be able to add people to the program before then.

**Comment by sarina** [comment]
I'm moving this to Done because we have already been inducting core contributors of all kinds into the program!
